// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PicPaySimplificado.Infra;

#nullable disable

namespace PicPaySimplificado.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250812134730_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("PicPaySimplificado.Models.CarteiraEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CPFCNPJ")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Limite")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Saldo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UsuarioTypeEntityType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Carteiras");
                });

            modelBuilder.Entity("PicPaySimplificado.Models.Entities.TransacaoEntity", b =>
                {
                    b.Property<Guid>("IdTransferencia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataTransacao")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("IdPagador")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("IdRecebedor")
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoTransacao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Valor")
                        .HasColumnType("TEXT");

                    b.HasKey("IdTransferencia");

                    b.HasIndex("IdPagador");

                    b.HasIndex("IdRecebedor");

                    b.ToTable("Transacoes");
                });

            modelBuilder.Entity("PicPaySimplificado.Models.Entities.TransacaoEntity", b =>
                {
                    b.HasOne("PicPaySimplificado.Models.CarteiraEntity", null)
                        .WithMany()
                        .HasForeignKey("IdPagador")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PicPaySimplificado.Models.CarteiraEntity", null)
                        .WithMany()
                        .HasForeignKey("IdRecebedor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
